image: node:14

stages:
  - build
  - release

cache:
  - node_modules

install_dependencies:
  stage: build
  script:
    - npm i

release:
  stage: release
  only:
    - master
  before_script:
    - npm install -g semantic-release debug @semantic-release/commit-analyzer @semantic-release/github @semantic-release/npm @semantic-release/release-notes-generator
  script:
    - npm run release
